name: Secret Scanning with Gitleaks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  secret_scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.3.2/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
        shell: bash

      - name: Run Gitleaks
        run: |
          gitleaks --path=. --verbose
        env:
          GITLEAKS_VERSION: v7.3.2
